### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by kairusds** [rockstorm101/gitweb-docker#1]
I set the config to default, except  for the logging, and this error keeps showing up whenever I access `/`:
```
gitweb-1    | 2024/02/29 07:50:46 [error] 38#38: *3 connect() to unix:/run/fcgiwrap/fcgiwrap.sock failed (111: Connection refused) while connecting to upstream, client: ***, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/fcgiwrap/fcgiwrap.sock:", host: "127.0.0.1:8080"
```

**Comment by rockstorm101** [comment]
Hi @kairusds, so sorry for taking so long to fix this. I just pushed a fix, please feel free to reopen this issue if it still doesn't work for you. After the fix, I am no longer able to reproduce the error.

Thanks a lot for taking the time for reporting issues.
